name: CI workflow
on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "develop" ]
jobs:
  build_and_compile_app:
    runs-on: ubuntu-latest
    container:
      image: docker:latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Validate the compilation process
        run: docker-compose up -d
  unit_tests:
    needs: build_and_compile_app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Run unit tests
        run: mvn test --file ./OcrExerciseGenerator-web/pom.xml
  integration_tests:
    needs: unit_tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Run integration tests
        run: mvn verify --file ./OcrExerciseGenerator-web/pom.xml
          
